# Generated by Django 4.1 on 2022-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_basket_user_alter_basketitem_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
