# Generated by Django 4.1 on 2022-11-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_apartment_order_comment_order_door_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonuses_used',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
