# Generated by Django 4.1 on 2022-11-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_basketitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Заказ создан'), ('processed', 'Заказ обрабатывается'), ('canceled', 'Заказ отменён'), ('delivery', 'Заказ у курьера'), ('delivered', 'Успешно доставлен'), ('finished', 'Заказ закончен')], default='created', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='work_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
