# Generated by Django 4.1 on 2022-12-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_basket_bonuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Заказ создан'), ('processed', 'Заказ обрабатывается'), ('canceled', 'Заказ отменён'), ('delivery', 'Заказ у курьера'), ('delivered', 'Успешно доставлен'), ('finished', 'Заказ закончен')], default='created', max_length=200)),
                ('datetime', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
    ]
