# Generated by Django 4.1 on 2022-12-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shop.order'),
        ),
    ]
