# Generated by Django 4.1 on 2022-12-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_orderstatuslog_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonuses_get',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
