# Generated by Django 4.1 on 2023-05-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_bonuses_get'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bonuses_get',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bonuses_used',
        ),
    ]
