# Generated by Django 4.1 on 2022-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_data',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Телефон'),
        ),
    ]
