# Generated by Django 4.1 on 2022-10-06 18:42

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_personal_data_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pictue',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_user_picture),
        ),
    ]
