# Generated by Django 4.1 on 2022-10-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_pictue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionoauth',
            name='expires_auth_token',
            field=models.DateTimeField(),
        ),
    ]
