# Generated by Django 4.1 on 2022-12-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_sessionoauth_expires_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonuses',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Бонусы'),
        ),
    ]
