# Generated by Django 4.1 on 2023-05-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_apartment_user_door_code_user_entrance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bonuses',
        ),
    ]
