# Generated by Django 4.1 on 2022-10-01 07:35

import catalog.models.catalog
import catalog.models.product
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Группа атрибутов',
                'verbose_name_plural': 'Группы атрибутов',
            },
        ),
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_show', models.CharField(choices=[('range', 'Диапазон'), ('dict', 'Чекбоксы'), ('radio', 'Радиокнопки')], default='dict', max_length=100, verbose_name='Тип отображения')),
                ('slug', models.SlugField(unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Имя атрибута',
                'verbose_name_plural': 'Имена атрибутов',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Путь')),
                ('text_value', models.CharField(blank=True, default='', max_length=200, verbose_name='Знаковое значение')),
                ('digitValue', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, verbose_name='Цифровое значение')),
                ('type_value', models.CharField(choices=[('digit', 'Цифровое'), ('letters', 'Знаковое')], default='letters', max_length=100, verbose_name='Тип значения')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
                ('active', models.BooleanField(default=False, verbose_name='Категория активна')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Описание')),
                ('small_description', models.TextField(blank=True, default='', verbose_name='Малое описание')),
                ('price', models.FloatField(default=0, validators=[catalog.models.product.validate_positiveValue], verbose_name='Цена')),
                ('old_price', models.FloatField(default=0, validators=[catalog.models.product.validate_positiveValue], verbose_name='Старая цена')),
                ('discount', models.FloatField(default=0, validators=[catalog.models.product.validate_positiveValue], verbose_name='Скидка')),
                ('active', models.BooleanField(default=False, verbose_name='Товар активен')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.product', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.product.get_upload_productImage, verbose_name='Изображение')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('main_image', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.catalog.upload_category_gallery, verbose_name='Изображение')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='catalog.attributegroup', verbose_name='Группа атрибута')),
                ('attribute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.attributename', verbose_name='Имя атрибута')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.attributevalue', verbose_name='Значение атрибута')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
    ]
