# Generated by Django 4.1 on 2022-10-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_collectionproduct_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionproduct',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
