# Generated by Django 4.1 on 2022-10-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_collectionproduct_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_parse',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
