# Generated by Django 4.1 on 2022-10-15 21:05

import catalog.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.product.get_upload_collection_image, verbose_name='Изображение'),
        ),
    ]
