# Generated by Django 4.1 on 2022-10-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_collectionproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionproduct',
            name='small_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
